# -*- coding: utf-8 -*-
"""really good? -- triple, deeper, batch norm, residual, Just conv two time pad

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yezG4MY_Ug_SeEYKPyuRG2tRRmlxNpvO
"""

!rm -rf TwoTimePad
!git clone https://github.com/matthiasgoergens/TwoTimePad.git
!rm -rf data *.h5
!cp -r TwoTimePad/data TwoTimePad/*.h5 ./
!pip install -q --no-deps tensorflow-addons

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 2.x
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

device_name = tf.test.gpu_device_name()

if device_name != '/device:GPU:0':
  print(
      '\n\nThis error most likely means that this notebook is not '
      'configured to use a GPU.  Change this in Notebook Settings via the '
      'command palette (cmd/ctrl-shift-P) or the Edit menu.\n\n')
  raise SystemError('GPU device not found')

with tf.device('/device:GPU:0'):
  import pathlib
  import re

  import tensorflow
  import tensorflow as tf
  from tensorflow import keras


  import pathlib
  import numpy as np
  import random
  from pprint import pprint

  # Train with longer later.
  # n = 25
  # n = 50

  np.set_printoptions(precision=4)


  # Idea:
  # Load corpus, and clean, convert into numbers
  # Repeatedly:
  #   create a batch of data
  #   train
  #   Optional: show current results.

  alpha =    " ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.?,-:;'()".lower()
  alphaRE = alpha.replace("-","\\-")

  assert len(alpha) == 46

  def load():
    text = ' '.join(f.open('r').read() for f in pathlib.Path('data').glob('*.txt')).lower()
    text = re.sub('\s+', ' ', text)
    text = re.sub(f'[^{alphaRE}]', '', text)
    return text

  def add(clear, key):
    return [(a+b) % len(alpha) for a, b in zip(clear, key)]

  def sub(cipher, key):
    return [(a-b) % len(alpha) for a, b in zip(cipher, key)]

  def clean(text):
    t = {c: i for i, c in enumerate(alpha)}
    return [t[c] for c in text]

  def toChar(numbers):
    return ''.join(alpha[i] for i in numbers)

  # toChar
  # (5, 125, 46)
  def toChars(tensor):
    (linesNums, charNum, alphaNum) = tensor.shape
    output = []
    # TODO: use gather https://www.tensorflow.org/api_docs/python/tf/gather?version=stable
    assert alphaNum == len(alpha)
    for lineNum in range(linesNums):
      chars = []
      for cN in range(charNum):
        (_, char) = max([(tensor[lineNum, cN, alphaN], alphaN) for alphaN in range(alphaNum)])
        chars.append(char)
      output.append(toChar(chars))
    return output

  def toChars_labels(labels):
    (linesNums, charNum) = labels.shape
    output = []
    for lineNum in range(linesNums):
      chars = []
      for cN in range(charNum):
        chars.append(labels[lineNum, cN])
      output.append(toChar(chars))
    return output


  def prepare(clear, key):
    assert len(clear) == len(key), (clear, key)

    # depth = len(alpha)

    # label = clear[len(clear)//2:len(clear)//2+1]
    return sub(clear, key)



  def sample(text, l):
    start = random.randrange(len(text) - l)
    return text[start:start+l]

  def samples(text, batch_size, l, drop_rate = 0.0):
    ciphersA = []
    ciphersB = []
    keys = []
    labelsA = []
    labelsB = []
    for _ in range(batch_size):
      clearA = sample(text, l)
      clearB = sample(text, l)
      key = [random.randrange(46) for _ in range(l)]

      cipherA = prepare(clearA, key)
      cipherB = prepare(clearB, key)
      # print(toChar(clear))
      # print(toChar(key))
      # print(toChar(add(clear, key)))
      # print(toChar(sub(add(clear, key), key)))
      ciphersA.append(cipherA)
      ciphersB.append(cipherB)
      labelsA.append(clearA)
      labelsB.append(clearB)

      key_corrupted_raw = [((random.random() >= drop_rate) * (k+1)) for k in key]
      key_corrupted = tf.convert_to_tensor(key_corrupted_raw) # Zero means corrupted..

      keys.append(key_corrupted)

    one_hot_ciphersA = tf.convert_to_tensor(ciphersA)
    one_hot_ciphersB = tf.convert_to_tensor(ciphersB)
    keys = tf.convert_to_tensor(keys)
    
    # print(one_hot_ciphers.shape)
    # print(one_hot_labels.shape)
    # print(len(one_hot_labels))
    return ([one_hot_ciphersA, one_hot_ciphersB, keys],
          [ tf.convert_to_tensor(labelsA),  tf.convert_to_tensor(labelsB)])

  # relu = keras.activations.relu # (alpha=0.1)
  relu = lambda: keras.layers.LeakyReLU(alpha=0.1)
  # keras.layers.Embedding

  from tensorflow.keras.layers import BatchNormalization, Concatenate, Embedding, Input, Dense, Dropout, Softmax, GlobalMaxPooling1D, MaxPooling1D, Conv1D, Flatten, concatenate, Bidirectional, LSTM, SimpleRNN, Add
  from tensorflow.keras.models import Sequential, Model
  import tensorflow_addons as tfa

  Maxout = tfa.layers.Maxout
  # window_size = 200
  # TODO: use convolution over 1d.
  # tf.keras.layers.Conv1D
  def make_model(n):
    inputA = Input(shape=(n,), dtype='int32', name="cipherA")
    inputB = Input(shape=(n,), dtype='int32', name="cipherB")
    inputKeys = Input(shape=(n,), dtype='int32', name="keysCorrupted")

    emb = Embedding(output_dim=len(alpha), input_dim=len(alpha), name="my_embedding")
    embKeys = Embedding(output_dim=len(alpha), input_dim=len(alpha)+1, name="my_embeddingKeys")
    embeddedA = emb(inputA)
    embeddedB = emb(inputB)
    embeddedKeys = embKeys(inputKeys)
    embedded = Concatenate()([embeddedA, embeddedB, embeddedKeys])

    # relud = lambda base: relu()(Dense()(base))
    # Idea is to bubble up better and better guesses for what letters we have locally.
    conv1 = lambda base: BatchNormalization()(Conv1D(
        filters=46*2*2 * 5, kernel_size=5,
        padding='same', strides=1)(
          base
        ))

    conv = lambda base: Add()([base, conv1(Maxout(46*2*2)(base))])
    # Not sure whether the eta abstraction is necessary?
    lstm_ed = (
      (conv(
      (conv(
      (conv(
      (conv(
      (conv(
      (conv(
      (conv(
      (conv(
      conv1(embedded)
    )))))))))))))))))

    totes_clear = (
      Softmax(name="clear")(Conv1D(
        filters=len(alpha), kernel_size=5,
        padding='same', strides=1)(
      lstm_ed
    )))
    totes_key = (
      Softmax(name="key")(Conv1D(
        filters=len(alpha), kernel_size=5,
        padding='same', strides=1)(
      lstm_ed
    )))
    #totes_cipher = (
    #  Softmax(name="cipher_again")(Conv1D(
    #    filters=len(alpha), kernel_size=1,
    #    padding='same', strides=1)(
    #  relu()(Conv1D(
    #    filters=len(alpha)*2, kernel_size=1,
    #    padding='same', strides=1)(
    #  relu()(Conv1D(
    #    filters=len(alpha)*2, kernel_size=1,
    #    padding='same', strides=1)(
    #  relu()(Conv1D(
    #    filters=len(alpha)*2, kernel_size=1,
    #    padding='same', strides=1)(
    #  concatenate([totes_key, totes_clear])
    #)))))))))
    model = Model([inputA, inputB, inputKeys], [totes_clear, totes_key])

    model.compile(
      optimizer='adam',
      loss='sparse_categorical_crossentropy',
      metrics=['accuracy'])
    return model

  import sys

  training_size = 2 * 10**4
  test_size = 10**3


from datetime import datetime
logdir = "logs/scalars/" + datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = keras.callbacks.TensorBoard(log_dir=logdir)

from keras.callbacks import *
# filepath="/content/gdrive/My Drive/two-time-pad/from_tutorial.hdf5"
weights_name = '/content/drive/My Drive/twotimepad/dropfix-triple-deeper-bn-res-just-conv.h5'
checkpoint = ModelCheckpoint(weights_name, verbose=1, save_best_only=False)

callbacks_list = [checkpoint, tensorboard_callback]

with tf.device('/device:GPU:0'):
  from google.colab import drive
  drive.mount('/content/drive')

  # Starting from higher.
  import sys
  # l = int(sys.argv[1])
  l = 100
  # l = window_size

l = 50

with tf.device('/device:GPU:0'):
  drop_rate = 100
  while True:
    model = make_model(l)
    try:
      model.load_weights(weights_name)
      print("Loaded weights.")
    except:
      print("Failed to load weights.")
      # raise

    print(model)
    print()
    text = clean(load())
    print(f"text size: {len(text):,} drop rate: {drop_rate}")
    print(f"Window length: {l}")

    print("Predict:")
    predict_size = 5
        # return ([one_hot_ciphersA, one_hot_ciphersB, keys_corrupted],
          # [labelsA, labelsB])
    # (ciphers_p, labels_p, keys_p) = samples(text, predict_size, l)
    (inputs_p, labels_p) = samples(text, predict_size, l, drop_rate/100.0)
    (ciphersA_p, ciphersB_p) = labels_p
    [predictA_p, predictB_p] = (model.predict(inputs_p))
    # clear, key, prediction
    pprint(list(zip(
        #toChars_labels(ciphers_p),
        #toChars(pred_cipher),
        # predict_size * [l * " "],

        toChars_labels(ciphersA_p),
        toChars(predictA_p),
        predict_size * [l * " "],

        toChars_labels(ciphersB_p),
        toChars(predictB_p),
        predict_size * [l * " "]
        )),
      width=250)
    print(f"Window length: {l}")
    # (ciphers_t, labels_t, keys_t) = samples(text, test_size, l)
    # print("Eval:")
    # model.evaluate(ciphers_t,  [ciphers_t, labels_t, keys_t], verbose=2)


    print("Training:")
    (inputs, labels) = samples(text, training_size, l, drop_rate/100.0)
    # (ciphers, labels, keys) = samples(text, training_size, l)
    model.fit(inputs, labels,
              # validation_data=(ciphers_t, [labels_t, keys_t]),
              callbacks=callbacks_list,)
    l = min(100, l+1)
    drop_rate = drop_rate + 1
    # model.save_weights(weights_name)
    # print("Saved weights")