#!/bin/bash

# This takes about 4 minutes for my 16 GiB corpus.
for name in worm unsong; do
    echo "Processing $name..."
    time cat "../examples/${name}.txt" | /usr/bin/time cargo run --release -- to-indices | pv > "../examples/${name}.bytes"
done
# time cat ../examples/worm.txt | /usr/bin/time cargo run --release -- to-indices | pv > ../examples/ciphertext-1.bytes
# time cat ../examples/unsong.txt | /usr/bin/time cargo run --release -- to-indices | pv > ../examples/ciphertext-2.bytes

