version: "2"

services:
  two-time-pad:
    image: two-time-pad
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/app
    ports:
      - 80:80
    user: "${UID}:${GID}"
